
    // TYPES FOR CURRENT USER

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CLEAR_USER = 'CLEAR_USER';


    // TYPES FOR CURRENT DEPARTMENT

export const SET_CURRENT_DEPARTMENT = 'SET_CURRENT_DEPARTMENT'; 
export const SET_PROBLEM_DEPARTMENT = 'SET_PROBLEM_DEPARTMENT';

    // TYPES FROM DEPARTMENT PROBLEMS 

export const SET_PROBLEM_DEPARTMENT_ID = 'SET_PROBLEM_DEPARTMENT_ID';